language: python
sudo: false
env:
    - AWS_DEFAULT_REGION=us-east-1

python:
    - "3.6"

before_install:
    - pip install --upgrade pip

install:
    - pip install -r requirements.txt

script:
    - pytest
